### ISSUE TITLE
When uploading a 5.8G file, the prompt Bad Gateway appears.

### ISSUE THREAD

**Issue by ainp** [mtlynch/picoshare#528] opened 2024-01-31 14:19 UTC
There is no problem in uploading a file of several hundred kilobytes, but when uploading a 5.8G file, the message "Bad Gateway" appears.
The information on the server is as follows:
[31/Jan/2024:14:07:36 +0000] "POST /api/entry?expiration=2999-12-31T00%3A00%3A00Z HTTP/1.1" 400 32
2024/01/31 14:08:12 upload.go:61: invalid upload: unexpected EOF

![截屏2024-01-31 22 18 27](https://github.com/mtlynch/picoshare/assets/9693302/264b114e-47ee-426e-9b5b-5db025b3b94e)

**Comment by mtlynch** [comment] 2024-02-02 00:44
Thanks for reporting this!

This is unfortunately a duplicate of #355, so I'm closing this in favor of the main ticket.

What's probably happening is that the server is crashing and restarting before the upload can finish. You might be able to work around it by allocation the server more RAM or CPU, but for the time being, PicoShare doesn't work so well on files >1GB.

**Closed by mtlynch** 2024-02-02 00:44 UTC
