### ISSUE TITLE
504 Gateway Time-out on 1.6GB File

### ISSUE THREAD

**Issue by W1BTR** [mtlynch/picoshare#595] opened 2024-09-10 21:30 UTC
Trying to host a debian system image. Upon uploading, it says the file is processing. Eventually it fails:

```
<html>
<head><title>504 Gateway Time-out</title></head>
<body>
<center><h1>504 Gateway Time-out</h1></center>
<hr><center>openresty</center>
</body>
</html>
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
```
![image](https://github.com/user-attachments/assets/d5131c7a-bed6-4c1a-8832-c225b4ef0d44)

**Comment by mtlynch** [comment] 2024-09-11 20:05
Thanks for reporting this!

This seems to be a dupe of https://github.com/mtlynch/picoshare/issues/355

The short answer is that PicoShare doesn't work well for files > 1 GB unless it's a fairly large server. I'm working on improving this, but the solution is non-trivial.

**Closed by mtlynch** 2024-09-11 20:05 UTC

**Comment by Tiritibambix** [comment] 2025-09-28 21:35
Hi.
Had this issue with a 500MB file.
I added this to my Nginx config and I had no more error message.

```
client_max_body_size 2G;
proxy_request_buffering off;
proxy_connect_timeout 300;
proxy_send_timeout 300;
proxy_read_timeout 300;

```

I haven't tried with lager files yet.
